name: Quick Tests

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - 'package*.json'

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run TypeScript check
      run: npm run typecheck
      
    - name: Check bundle size
      run: |
        npm run build
        echo "### Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Size |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|------|" >> $GITHUB_STEP_SUMMARY
        echo "| First Load JS | $(du -sh .next/static/chunks/pages/*.js | awk '{total += $1} END {print total "KB"}') |" >> $GITHUB_STEP_SUMMARY
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        
    - name: Run smoke tests
      run: |
        npx playwright install chromium
        npx playwright test tests/e2e/simple-console-test.spec.ts --project=chromium
      env:
        CI: true